version: '3.8'

services:
  app:
    build: .
    container_name: server
    volumes:
      - .:/app
    command: ["./main"]
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./data:/data
    command: ["sqlite3", "/data/desafio.db"]